Vagrant.configure("2") do |config|
  config.vm.define :machine1 do |machine1|
    machine1.vm.box = "bento/ubuntu-16.04"
    machine1.vm.network :private_network, ip: "192.168.100.4"
    machine1.vm.hostname = "machine1"
  end
  config.vm.define :machine2 do |machine2|
    machine2.vm.box = "bento/ubuntu-16.04"
    machine2.vm.network :private_network, ip: "192.168.100.5"
    machine2.vm.hostname = "machine2"
  end
end