Vagrant.configure("2") do |config|
  config.vm.define :clienteUbuntu do |clienteUbuntu|
  clienteUbuntu.vm.box = "bento/ubuntu-16.04"
  clienteUbuntu.vm.network :private_network, ip: "192.168.100.2"
  clienteUbuntu.vm.hostname = "clienteUbuntu"
  clienteUbuntu.vm.provider :virtualbox do |vb|
    vb.gui = true
  end
  end
  config.vm.define :servidorUbuntu do |servidorUbuntu|
  servidorUbuntu.vm.box = "bento/ubuntu-16.04"
  servidorUbuntu.vm.network :private_network, ip: "192.168.100.4"
  servidorUbuntu.vm.provision "shell", path: "script.sh"
  servidorUbuntu.vm.hostname = "servidorUbuntu"
  servidorUbuntu.vm.provider :virtualbox do |vb|
    vb.gui = true
  end
  end
  end